language: node_js
node_js:
- 10.16.3
deploy:
  provider: heroku
  api_key:
    secure: ZJa/du8P+4PtMkH3fHIuu2Bfm3na3woFrpbrtrCxCOQCPiOwcQ/EThUGTOlY4FOTy4F0sFnIfTA+LysXgV7iEWfCHbH/PXyDyD+f72b4Y+KbUzeY4OeVxj+5FWDXqN2om6tnxKqyv+Zt3ePEVKV0XQbWS/5d7uPTvCZDZIBhrE85jkyy2H+cZ4qHnckvmVmTNhVLyZBhzB1o/tTHL+SlK357O3qFM/nI/xaiKEuXhzdQisUSCSgQKVVwxHn7pV2pm92/D4vvrbvaLvJWuffQ626Mp7MTQPc6TQN/45QkrhXnqodt0rB6GFEybNt8ur/Dui1uANGyWAUEq9sfY5cBWCNpZVeGjhnOUPVZ3bE3uSwmHhrtK9Yo80i0gVneKkHB6+WPplDXxzbkr+SseEXyE/qbcEf+2/qaWitULpkLXQHEMKZxJuSWvKIPacv7mErAey1qbT9iEIelJ5q5m+ihW3Ee0kXaULU4yTepS/QmImKKj1yeQNFConKEdXs+9WDTFDU7v3H75KmrjzFDAOptdyEdwuSZ9Zmmda6LPA5sDcvt0cONBKKEKSDryPIhpnhVlO/F+3d7+VcYDKSBSjPSdC+E7F2V3vn2Xau4fApx/RcHD50EsNMl9MfGu7him5zYmDqFAf++w9CX8qI+7tkBfRE3Xiqpdkj5g+xjikrr7JA=
  app: one-pesewa
  on:
    repo: McAngelo/one-pesewa
run:
- restart
- rake cleanup
