language: node_js
node_js:
- 10.16.3
deploy:
  provider: heroku
  api_key:
    secure: Xstc1n32+exnv3V5t0mLDksGJIJQg8s2eRk6enLiW9YLbK8QBa2TvvSS03rUXSgig+Ows3TOgPuuJfq24C00TMQqSEAKrQwHDPnbLz7AyV9VtH8YgSv35f1FqYPxNt+9YNfetINkfuxDZbR54N3xD0sTHFCgt0zJy0Q/663NQLKW0TNZaxu05/PqLbx3kczscsXv0g/uUyWWZ+X48WgD3Iss28NWnRazzewwDOaKjlxnQCd95HxPJuvMULFdphbZVAcGFRj9EvoII0kTnFz4ogIr3MQcDoumZCm+znvPK/YCAZWUpZ6V62D98hhVb/ZjzSUwoUtPl+2ONTd0eGjoYFj7hlev+N8cARGQQIaenYlXzboiin89TNJVoZrb/U5jaiekrXyOXcf2ihHBNkCWWugMQ4PfWaF0nYepjBkArHQtd4DekDP4FQcFi19iNyLgObodnUFNf3l0p8K2XKZnZ1cl9l3SyNeKx9URGH1BmCMa+SFhqXGEBY0Ab5XFJpVGnYdAH52myxhBuRuGsRFPtd1RR/1yXjO4Zt2+43Fvosrr/oo/Jix9HvhW3r74DLpdmjKQkR563QFz08ldlzOhregEfO4yEvsGZSqbbTFn8EgUFpXVzKrpb06uGTIJbP33+voMHDg/4yifC77s0rGkupEQ7vGFgvVcpPRRhq1kVc8=
  app: one-pesewa
  on:
    repo: McAngelo/one-pesewa
run:
- restart
- rake cleanup
