language: node_js
node_js:
- '10.16.3'
deploy:
  provider: heroku
  api_key:
    secure: ZkNfcwgu6iTgXKn44ieCrZ8WF3Oshh6nzUiCypibj/88X3XJDqjG7sGeHIiZ5xD9R/bdhAaJB2otp+KN88TEScemrlu7S+SqRNsHPQZdgaZEabrBO8Bka1tT3KYhxTa6I8nERfP4GOOqRcTupFgwpwKH3vBr4e1ikmWz7Ngn6goWlRGP3NcXQXW8a1em3DKM82hT8QBmNGEPlYC73E0oYYlXh5TRCechM7tqq1rTvC6My/JDAPI6T2mkuv7O5W4gUnZbQJt6DtqcOQGx3CF9I3RRxEgxz/jT3oclDqXk91RozqXRk9G4bGbZJFBiBEDj1gAbpkOwzs9z5vLAU5keEpXVq8SQMQK0ADXTA9dEK2FkHW55MYeeZ7Yg4ThJ3jk5OXfqUcjSGrJ7HV5bBNiEktyENKJ3ykOON8ohqYUPKcarOva3jPFkZegCDsjcigAer6RZUztb/HIAiFDeM3lITJ1o4ML0gV+gVdbUoIW+0qMcVaOPi1MmjF6baBAGw8YgihHys1SAZhMWPi48s98YAw+6nsse0Tjkg29lFyFOlKcBrbRFzj0oM2nfbUgYEyjTKFDtR2uFTniFvUa2/P66eYQ3yVp6pgqpT3+iu3bieZLm9uP8JWJCPqvYnVRC3RFYfpp2LWDm4OeA9ahFkncHGHjqlfpAF9GSM3xKURjysvI=
  app: one-pesewa
  on:
    repo: McAngelo/one-pesewa
run:
- restart
- rake cleanup
